### ISSUE TITLE
Arrange workshop with ADDI for ECR event in January

### ISSUE THREAD

**Issue by CAmaat** [UKDRI/ECR-Informatics-Committee#12]

**Comment by CAmaat** [comment]
ADDI workshop is now confirmed. ADDI needs participants' details, which is now being asked consent for in the sign-up form. Christina is also collecting consent from those who did already sign up. Things to be discussed with ADDI:
- title workshop
- detailed content
- run-through at the venue

Christina will arrange a meeting with the ADDI team; Amonida & Mateus will join, others optional.

**Comment by H-Mateus** [comment]
Event concluded
