### ISSUE TITLE
reach out to sponsors after ECR event confirmation

### ISSUE THREAD

**Issue by CAmaat** [UKDRI/ECR-Informatics-Committee#4]

**Comment by H-Mateus** [comment]
I'll copy over a list of potential sponsors we had on HackMD:

# Potential sponsor list for informatics meeting

## Levels of sponsorship

#### Silver
- £1000
    - Have logo on the programme
    - Logo and link to website on the meeting website in the sponsors section
    - sponsored coffee break or lunch, as noted in programme
#### Gold
- £3000
    - Have logo on the programme
    - Logo and link to website on the meeting website in the sponsors section
    - Exhibition table up in the same room as poster viewing for the entire event
    - Logo on conference merchandise (ie. tote bag)
#### Platinum
- £20,000
    - Sponsorship of the full event
    - Everything mentioned in previous tiers
    - A 15 minute talk
    - Can negotiate anything else


*Other notes*
- Whole event
- Second day lunch
- Sponsor keynote talk/session?
- Stand/s & tiers (bronze/silver/gold)

### Software

- Posit: https://posit.co/
- JetBrains: https://www.jetbrains.com/
- GitHub: https://github.com/
- GitLab: https://about.gitlab.com/
- Git kraken https://www.gitkraken.com/
- Seqera (Nextflow owner): https://seqera.io/

### Cloud

- AWS: https://aws.amazon.com/
- DNAnexus: https://www.dnanexus.com/
- Microsoft/Azure: https://azure.microsoft.com/en-gb/
- Google via their cloud life sciences program https://cloud.google.com/life-sciences

### Omics platforms

- Takara: https://www.takarabio.com/
- 10X: https://www.10xgenomics.com/
- ParseBio: https://www.parsebiosciences.com/
- nanoString https://nanostring.com/
- Lexogen https://www.lexogen.com/
- Oxford Nanopore https://nanoporetech.com/
- PacBio https://www.pacb.com/
- Singleron https://singleron.bio/
- Vizgen https://vizgen.com/
- Pixelgen technologies https://www.pixelgen.com/
- Proteome sciences https://www.proteomics.com/

### Hardware

- Nvidia: https://www.nvidia.com/en-gb/
- Withings ([UK based has DRI partnership](https://ukdri.ac.uk/news-and-events/new-research-explores-how-tracking-sleep-with-an-innovative-sensor-may-help-diagnose-dementia) https://www.withings.com/uk/en/

### Pharma

- Astex Pharmaceuticals ([UK DRI has partnership with](https://ukdri.ac.uk/news-and-events/new-partnership-with-astex-pharmaceuticals-to-accelerate-progress-in-dementia-research)
- Genentech https://www.gene.com/scientists/neuroscience
- Biognosys https://biognosys.com/services/therapeutic-areas/#neuroscience

### AI
- Cosyne therapeutics (london based) https://cosyne.com/

**Comment by H-Mateus** [comment]
As an update, I've sent out emails to almost everyone company on the above list (couldn't find any sort of email for a few 🤷)

I'll feed back when/if I hear back
